/// Public surface of the account-free ArtKiddo core.
///
/// Files under `src/` remain implementation details. Private mobile adapters
/// may depend on these typed contracts and repositories, but this package never
/// imports a provider SDK or a private backend identifier.
library;

export 'src/presentation/config/app_capabilities.dart';
export 'src/presentation/config/bootstrap_configuration.dart';
export 'src/presentation/config/cloud_services.dart';
export 'src/presentation/bootstrap/artkiddo_bootstrap.dart';
export 'src/contracts/auth_gateway.dart';
export 'src/contracts/gallery_sharing.dart';
export 'src/contracts/household.dart';
export 'src/contracts/object_storage.dart';
export 'src/contracts/remote_media.dart';
export 'src/contracts/sync_backend.dart';
export 'src/contracts/trash.dart';
export 'src/local/database/app_database.dart';
export 'src/domain/app_failure.dart';
export 'src/domain/action_result.dart';
export 'src/local/storage/local_vault.dart';
export 'src/presentation/locale/locale_provider.dart';
export 'src/presentation/navigation/app_shell.dart';
export 'src/presentation/theme/app_theme.dart';
export 'src/presentation/providers/core_providers.dart';
export 'l10n/generated/app_localizations.dart';
export 'src/local/repositories/children_repository.dart';
export 'src/local/repositories/local_trash_repository.dart';
export 'src/domain/child.dart';
export 'src/local/repositories/masterpieces_repository.dart';
export 'src/domain/masterpiece.dart';
export 'src/sync/conflict_resolution.dart';
export 'src/sync/sync_outbox.dart';
export 'src/sync/vault_meta.dart';
export 'src/sync/sync_engine.dart';
export 'src/presentation/async_action.dart';
export 'src/presentation/theme/app_tokens.dart';
export 'src/presentation/navigation/pending_intent.dart';
export 'src/presentation/navigation/shell_tab_request.dart';
export 'src/presentation/utils/app_settings_launcher.dart';
export 'src/local/audio/audio_player_service.dart';
export 'src/local/audio/audio_recorder_service.dart';
export 'src/local/logging/log.dart';
export 'src/local/storage/image_derivatives.dart';
export 'src/local/repositories/trash_repository.dart';
export 'src/presentation/ui/app_button.dart';
export 'src/presentation/ui/artwork_card.dart';
export 'src/presentation/ui/child_row.dart';
export 'src/presentation/ui/discard_guard.dart';
export 'src/presentation/ui/error_presenter.dart';
export 'src/presentation/ui/filter_chip_row.dart';
export 'src/presentation/ui/formatters.dart';
export 'src/presentation/ui/gallery_cell_extent.dart';
export 'src/presentation/ui/highlight_once.dart';
export 'src/presentation/ui/state_block.dart';
export 'src/presentation/children/child_actions_sheet.dart';
export 'src/presentation/children/child_editor_controller.dart';
export 'src/presentation/children/child_editor_screen.dart';
export 'src/presentation/children/children_providers.dart';
export 'src/presentation/children/children_screen.dart';
export 'src/presentation/children/trash_controller.dart';
export 'src/presentation/children/trash_screen.dart';
export 'src/presentation/gallery/artwork_screen.dart';
export 'src/presentation/gallery/artwork_zoom_screen.dart';
export 'src/presentation/gallery/camera_capture_screen.dart';
export 'src/presentation/gallery/capture_controller.dart';
export 'src/presentation/gallery/capture_screen.dart';
export 'src/presentation/gallery/gallery_actions.dart';
export 'src/presentation/gallery/gallery_providers.dart';
export 'src/presentation/gallery/gallery_screen.dart';
export 'src/debug/demo_seed.dart';
