import 'dart:convert';
import 'dart:io';

/// Produces the small architecture index used by agents at conversation start.
///
/// The script intentionally reads only manifests and the candidate public
/// source tree. It has no dependency on the historical private checkout.
void main(List<String> arguments) {
  final checkOnly = arguments.contains('--check');
  final root = Directory.current.absolute;
  final sourceRoots = <Directory>[
    Directory('${root.path}/app/lib'),
    Directory('${root.path}/packages/artkiddo_core/lib'),
  ];
  final inputFiles = <File>[];
  for (final directory in sourceRoots) {
    if (directory.existsSync()) {
      inputFiles.addAll(_dartFiles(directory));
    }
  }
  for (final path in <String>[
    'pubspec.yaml',
    'app/pubspec.yaml',
    'packages/artkiddo_core/pubspec.yaml',
    'packages/artkiddo_core/drift_schemas/v11.json',
  ]) {
    final file = File('${root.path}/$path');
    if (file.existsSync()) inputFiles.add(file);
  }
  inputFiles.sort((a, b) => _relative(a.path).compareTo(_relative(b.path)));

  final publicSource = inputFiles
      .where((file) => file.path.contains('/lib/'))
      .map((file) => file.readAsStringSync())
      .join('\n');
  final forbidden = <String, int>{};
  for (final token in <String>[
    'package:http',
    'package:mime',
    'SERVICE_ROLE_KEY',
    'DATABASE_URL',
  ]) {
    final count = token.allMatches(publicSource).length;
    if (count > 0) forbidden[token] = count;
  }

  final coreFiles = _dartFiles(
    Directory('${root.path}/packages/artkiddo_core/lib'),
  );
  final exports =
      coreFiles
          .firstWhere(
            (file) => file.path.endsWith('/lib/artkiddo_core.dart'),
            orElse: () => File(''),
          )
          .existsSync()
      ? File('${root.path}/packages/artkiddo_core/lib/artkiddo_core.dart')
            .readAsLinesSync()
            .where((line) => line.trimLeft().startsWith('export '))
            .map((line) => line.trim())
            .toList()
      : <String>[];
  final schema = File(
    '${root.path}/packages/artkiddo_core/lib/src/local/database/app_database.dart',
  );
  final schemaVersion = schema.existsSync()
      ? RegExp(
          r'schemaVersion\s*=>\s*(\d+)',
        ).firstMatch(schema.readAsStringSync())?.group(1)
      : null;
  final providerFiles = coreFiles
      .where(
        (file) =>
            file.path.endsWith('_providers.dart') ||
            file.path.endsWith('_bootstrap.dart'),
      )
      .map((file) => _relative(file.path))
      .toList();
  final testFiles = _dartFiles(
    Directory('${root.path}/packages/artkiddo_core/test'),
  )
    ..addAll(_dartFiles(Directory('${root.path}/app/test')));
  testFiles.sort((a, b) => _relative(a.path).compareTo(_relative(b.path)));

  final fingerprint = _fingerprint(inputFiles);
  final buffer = StringBuffer()
    ..writeln('# Generated public workspace inventory')
    ..writeln()
    ..writeln(
      'Do not edit this file. Regenerate with `dart run tool/generate_inventory.dart`.',
    )
    ..writeln('Use `dart run tool/generate_inventory.dart --check` in CI.')
    ..writeln()
    ..writeln('Input fingerprint: `$fingerprint`')
    ..writeln()
    ..writeln('## Members')
    ..writeln()
    ..writeln('- `app` — local composition shell')
    ..writeln('- `packages/artkiddo_core` — public local package')
    ..writeln()
    ..writeln('## Public exports (${exports.length})')
    ..writeln();
  for (final export in exports) {
    buffer.writeln('- `$export`');
  }
  buffer
    ..writeln()
    ..writeln('## Composition and schema')
    ..writeln()
    ..writeln('- Provider/composition files: ${providerFiles.length}')
    ..writeln('- Drift schema version: `${schemaVersion ?? 'unknown'}`')
    ..writeln(
      '- Dart source files: ${coreFiles.length + _dartFiles(Directory('${root.path}/app/lib')).length}',
    )
    ..writeln('- Tests: ${testFiles.length}')
    ..writeln()
    ..writeln('## Test files')
    ..writeln();
  for (final file in testFiles) {
    buffer.writeln('- `${_relative(file.path)}`');
  }
  buffer
    ..writeln()
    ..writeln('## Public boundary scan')
    ..writeln()
    ..writeln(
      forbidden.isEmpty
          ? 'Forbidden provider/backend markers: none.'
          : 'Forbidden markers found: ${jsonEncode(forbidden)}',
    );

  final output = File('${root.path}/docs/architecture/generated-inventory.md');
  final content = buffer.toString();
  if (checkOnly) {
    if (!output.existsSync() || output.readAsStringSync() != content) {
      stderr.writeln('generated-inventory.md is stale; run the generator.');
      exitCode = 1;
    }
    if (forbidden.isNotEmpty) {
      stderr.writeln('public boundary scan failed: ${jsonEncode(forbidden)}');
      exitCode = 1;
    }
    return;
  }
  output
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(content);
  if (forbidden.isNotEmpty) {
    stderr.writeln('public boundary scan failed: ${jsonEncode(forbidden)}');
    exitCode = 1;
  }
}

List<File> _dartFiles(Directory directory) {
  if (!directory.existsSync()) return <File>[];
  return directory
      .listSync(recursive: true)
      .whereType<File>()
      .where((file) => file.path.endsWith('.dart'))
      .toList();
}

String _relative(String path) {
  final root = Directory.current.absolute.path;
  final absolute = File(path).absolute.path;
  return absolute.startsWith('$root/')
      ? absolute.substring(root.length + 1)
      : absolute;
}

String _fingerprint(List<File> files) {
  var hash = 0xcbf29ce484222325;
  for (final file in files) {
    final bytes =
        utf8.encode('${_relative(file.path)}\n') + file.readAsBytesSync();
    for (final byte in bytes) {
      hash ^= byte;
      hash = (hash * 0x100000001b3) & 0xffffffffffffffff;
    }
  }
  // Dart's VM uses signed machine integers for bitwise operations. Normalize
  // before rendering so the inventory never emits a negative fingerprint when
  // the FNV-1a high bit is set.
  return BigInt.from(hash).toUnsigned(64).toRadixString(16).padLeft(16, '0');
}
